### PR TITLE
Issue 35 Media Deletion

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
Stages and media delete button

### CODE REVIEW

**Review by gloriajw — APPROVED** [review]

**Comment by gloriajw** [comment]
How do we deal with history replay with deleted media? Is there an empty box or something denoting a missing avatar?

**Comment by nguyenhongphat0** [comment]
Yes when we replay a record with missing avatar, an empty box will be shown. This can be solve by delete the avatar from the database only (so that user won't see them in the Media list) and keep their existence in file storage. However this might fill our storage with unused media, which is also not good 🤔

**Comment by helenvarley** [comment]
> How do we deal with history replay with deleted media? Is there an empty box or something denoting a missing avatar?

normally we only delete media that we really don't need, such as trial versions of something. traditionally most players never delete media that's been used in a show. it could happen, of course, & phat's solution is a good one at least initially, to see how much of a storage issue this would create.
another solution can be to have a default "missing media" icon rather than an empty media box ... some kind of blob or indeterminate shape as a stand-in?

**Comment by vickis** [comment]
yes this is a good work around - it maybe that there is a warning that
unless all the media remains the record will show a stand-in icon
if the recording is super crucial then a screen recording would have to be
made :)

**Comment by nguyenhongphat0** [comment]
Yes we can fallback to another image if the file is missing. I'm using this avatar (I found it on Github's 404 page 😅) for now, if you want to replace it with something else just give me the file, thank you 🙏  
notfound

**Comment by vickis** [comment]
cute!

**Comment by elisadcg** [comment]
This image is very attach to github. I suggest a new one for UpStage. Remind the green UpStage and show the same movement with his arms (tentacle...).
Screenshot_20210518_121015

**Comment by vickis** [comment]
cool :)

**Comment by nguyenhongphat0** [comment]
I replaced the octocat with your image @elisadcg 🙌

**Pull request merged**
