### PR TITLE
7-A39

### PR DESCRIPTION
**Pull request by paul-rohrlach**
Feature Release 7

### CODE REVIEW

**Comment by vickis** [comment]
ooh a little masculine droid instead of an almighty female cyborg (7 of 9
... i know it was crossing genres but well  ... ;)

**Comment by helenvarley** [comment]
maybe paul is a star wars purist?

**Comment by paul-rohrlach** [comment]
@helenvarley, I AM Haha. 

But really, I'm just pulling droid names from the internet.

**Comment by vickis** [comment]
dang - i am fluid in the intergalactic realm ... but defer to the Paul's
penchant for fantasy purism
don't want to be a sleemo about the sci-fi naming conventions ;)

**Comment by nguyenhongphat0** [comment]
I vote yes. There aren't many new features this this release, but it provides more stability and bug fixes 🙌

**Pull request merged**
