### PR TITLE
Enhance GraphQL Connections

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
There was some issue when upload a media, the created_on got the value of 9 days ago, instead of the current date 🤔 After restarting the upstage service, the issue seems to be gone. But I figure it out, the backend was built with the main branch all the time (it should use the R1-2021). These changes need to be sync from main to R1-2021 to match the frontend params

### CODE REVIEW

**Comment by paul-rohrlach** [comment]
@nguyenhongphat0 what you describe in the PR summary and what your changes do appear to be at odds.

Can you update your explanation of the change such that it reflects what the change actually does?

In other words, you're describing fixing a timestamp issue but the actual changes also seem to do other things like adding Python classes and fixing a "blank users page" problem.

**Comment by nguyenhongphat0** [comment]
Sorry for confusing you, Paul. I created this branch to fix the created_on `9 days ago` issue. But after restarting the upstage.service the issue seem to be gone, but I relize that the source code on the R1-2021 was behind the front end (because when developing UI for the R1-2021, I point to app1 backend, it without restarting since the last branch switching the app1 backend was using the main branch all the time). So these change are needed for the R1-2021 UI working properly

I changed the title of the pull request to match what should be changes, sorry for all the mess 😅

**Comment by paul-rohrlach** [comment]
Okay.

From what I understand, `main` is ahead of `R1-2021` in terms of feature set and typically, we wouldn't want the active development branch to end up in a release branch.  

I'll have to defer to @gloriajw as to whether this change is acceptable or not.

**Comment by nguyenhongphat0** [comment]
Thanks Paul!

**Review by gloriajw — APPROVED** [review]

**Pull request merged**
