### PR TITLE
Issue 335 Media Voice

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
We can now save voice in backstage, so when we assign that avatar to a stage, the saved voice will be the default voice of that avatar

Screenshot 2021-05-17 at 20 19 20

And I refactor the upload flow as well, to reuse the same media form

### CODE REVIEW

**Review by gloriajw — APPROVED** [review]

**Comment by helenvarley** [comment]
awesome! you are so amazingly fast, phat!! :smile: 
when can we test this? will it go into R2D2 or do we need to test on dev-app?

**Comment by nguyenhongphat0** [comment]
Yes it's already on dev-app. But for these avatar that already assigned to stage, after save the voice setting you will have to save the stage's media again for the changes apply (like how multiframe works)
I think I should change the way things got cloned right now 😩

**Comment by helenvarley** [comment]
ok, i will test on dev-app. and that sounds good, to save the stage media again - in fact we are used to this from the old platform: if ANY changes were made to the stage, e.g. more media or changed voices, then the stage had to be saved and everyone had to reload to see the changes. 
(actually - there was a button on the stage edit interface that was a "save and reload" button, which forced the stage to reload for everyone. we didn't use this in live performances (except in one show, when there was an "explosion" and they used the force reload as a way for the audience to experience the explosion - it was quite effective!) but it can be quite handy in rehearsals. maybe we need that ...)

**Comment by nguyenhongphat0** [comment]
Oops I made the changes already 🤣 And it is necessary for stages to be assigned to media (in the past we can only assign media to stages, in 1 direction). Now you don't have to re-save the stage after you made changes to the media any more 😅

**Pull request merged**
