### PR TITLE
Vanity URLs

### LINKED ISSUE #409: Vanity URLs
It would be nice to be able to access stages via a vanity URL like:
```/my-stage```
Rather than having to remember the full path like:
```/V4.0/ui/live/my-stage```

### PR DESCRIPTION
**Pull request by paul-rohrlach**
Closes #409

### CODE REVIEW

**Comment by paul-rohrlach** [comment]
@gloriajw assuming you accept these changes, could you also deploy them?  I don't have access to the web servers (AFAIK)

**Comment by paul-rohrlach** [comment]
I also wonder whether we don't just put the UI on the root path?

**Review by gloriajw — APPROVED** [review]

**Comment by gloriajw** [comment]
Do you mean our UI on the root path?

**Comment by paul-rohrlach** [comment]
I mean simply having the UI on the root path of NGINX rather than via `/V4.0/live/ui/...`

**Comment by nguyenhongphat0** [comment]
That would be more convenience 👍

**Pull request merged**
