### PR TITLE
Basic Stage

### LINKED ISSUE #65: Basic Stage
Create a basic stage based on CSS3 with the intention of utilizing it with [anime.js](https://animejs.com/)

### PR DESCRIPTION
**Pull request by paul-rohrlach**
Closes #65

### CODE REVIEW

**Comment by paul-rohrlach** [comment]
@elisadcg and @petyrv as you work on this, it'd be good if you could periodically add screenshots to the discussion here 😄

**Comment by paul-rohrlach** [comment]
@elisadcg and @petyrv please mark this as 'ready for review' when you are finished

**Comment by paul-rohrlach** [comment]
@elisadcg per conversation with @gloriajw please move all files from `ui/` to `ui/static`

**Comment by paul-rohrlach** [comment]
@elisadcg sorry, I wasn't clear.

all files should now be under `ui/static` and nothing should still be under  `ui/`

**Review by petyrv — APPROVED** [review]

**Pull request merged**
