### PR TITLE
Live Demo Stage

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
Building the live stage with static assets for demo, here: http://159.89.19.111/V2.0/ui/live. Which includes:

- Chat window
- Toolbox: avatar, prop, backdrop
- Integrate mqtt protocol for sending/receiving chat message/stage message
- Integrate anime.js for avatar animation

### CODE REVIEW

**Review by gloriajw — APPROVED** [review]

**Comment by helenvarley** [comment]
trying to send this via slack, but it tells me i'm offline, when i'm not ...i am in the demo stage now - yippee!! looks great! :smile: but i see "connecting" all the time at the top right, with a flashing dot - does that mean it's still connecting, or is that like a "live" signal?

**Comment by paul-rohrlach** [comment]
@helenvarley Slack is currently experiencing problems: https://status.slack.com/2021-01/9ecc1bc75347b6d1

Must be the first day back 😆

**Comment by helenvarley** [comment]
or slack is still on holiday ... that's a bit slack! ;)

**Comment by vickis** [comment]
hello all
amongst finishing the video work for our TechCul app i have also been slack
at getting my IP address to you (but super busy on offline projects (local
installs)

here it is! - 111.69.60.36 <https://whatismyipaddress.com/ip/111.69.60.36>

excited to see where you have got to!!
vX :)

**Comment by nguyenhongphat0** [comment]
Hello everyone,
The CONNECTING status means your IP can't reach the mqtt broker. Please send your IP address to Gloria so that she can add you to the whitelist. If the status turned to LIVE then it's okay.

**Pull request merged**
