### PR TITLE
Issue 57 Avatar Voice

### LINKED ISSUE #57: avatar voices
as a logged-in player, i expect to be able to select a voice for an avatar from a vast range of voices with a variety of intonation, pitch and accent.

on stage, avatar text should be spoken in that avatar's voice and heard simultaneously by all players and audience members on that stage.

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
We have the new "Voice setting" inside context menu to open this dialog, and after that these bubble of this avatar will be spoken using SpeechSynthesis API
Screenshot 2021-05-03 at 14 45 34

Resolve #57

### CODE REVIEW

**Comment by helenvarley** [comment]
can we try it? i don' find it on dev-app ... ?

**Comment by nguyenhongphat0** [comment]
Not yet, Helen. This pull request must be Approved and Merged into `R2-2021`, only after that the code will be rolled out to devapp1 😅 
I will let you know when you can test it

**Comment by helenvarley** [comment]
i try to be patient :laughing

**Comment by vickis** [comment]
it is indeed exciting! :)

**Review by paul-rohrlach — APPROVED** [review]

**Pull request merged**
