### PR TITLE
Link inside chat bubble

### LINKED ISSUE #39: stage: clickable links in chat / text
as a logged-in player or audience member, i expect to be able to paste a link into the chat window and that others on the stage can click on it and have it open in a new window.

links posted by logged-in players as "thoughts" or "shouts" should also be clickable in the chat window, the same as when posted as ordinary speech or audience text.

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
Sorry I forgot about the bubble 😅 
Resolve #39

### CODE REVIEW

**Review by gloriajw — APPROVED** [review]

**Comment by helenvarley** [comment]
cool, does this mean links would be clickable in the avatar's speech bubble as well as in the chat window? :+1:

**Comment by nguyenhongphat0** [comment]
Yes, link will be clickable in both. But this is on R2-2021

**Comment by helenvarley** [comment]
i look forward to it!

**Comment by nguyenhongphat0** [comment]
R2-2021 is on https://dev-app1.upstage.org.nz/V4.0/ui/live/demo, you can take a look. But the stage is not consistence right now 😅

**Pull request merged**
