### PR TITLE
Issue 29 Player and Audience counter

### LINKED ISSUE #29: stage: player / audience counter
as either audience or player, i expect to be able to see a counter on stage showing the number of players and audience currently on that stage at any time. i expect this counter to update in real time if players or audience enter or leave the stage.

additionally, this counter would allow me to see the names of players and audience members (if they have chosen to have a name) - for example a dropdown list of names appears when i click on the number.

currently in UpStage this counter appears above the chat window:

image

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
Resolves #29, #14 

Screenshot 2021-06-17 at 11 54 36
Screenshot 2021-06-17 at 11 55 28

### CODE REVIEW

**Comment by vickis** [comment]
great Phat

two ss in Press ;)

**Comment by helenvarley** [comment]
& it would be better to use "click" rather than press, as i think everywhere else we use "click"
great counters!!

**Comment by nguyenhongphat0** [comment]
Thank you! But I don't understand what we are talking about the press and click stuff 😅

**Comment by nguyenhongphat0** [comment]
Oh I see it now, changed to "Click" 😅 
Thank you 🙏

**Review by paul-rohrlach — APPROVED** [review]

**Pull request merged**
