### PR TITLE
Player/Audience Counter

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
Screenshot 2021-04-02 at 15 00 00

### CODE REVIEW

**Comment by helenvarley** [comment]
looks great! 
will the "guest" one have a number beside it, e.g. 12 guests? (this would be more practical than having a whole list of guest, guest, guest etc)

**Comment by nguyenhongphat0** [comment]
The Guest can change their nicknames as well Helen. Their chat nickname will be shown there as soon as they change it

**Review by gloriajw — APPROVED** [review]
You did this without a back-end component, interesting! We may want to, in the future, keep stats on the number of attendees, and how many connections failed/reformed, etc. in the database. Not something to worry about now.

**Comment by nguyenhongphat0** [comment]
Yes Gloria. There is some work around about the `unexpected leaving stage` situation, but it's work quite okay now. In the future I will make the backend read the counter from the mqtt broker, and persist it to database 👌

**Comment by helenvarley** [comment]
do we also have the possibility for audience (guests) to be anonymous? this would be good - that they can choose a nickname if they want when they enter, but they can also come without a nickname?

**Pull request merged**
