### PR TITLE
Stage cover image

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
Sorry I promised to do this a long time ago but I forget, primarily because we don't have a Github issue for this, we just discussed about it on Slack 😅
Pick a cover image in Stage Management, and your stage's loading screen will look like this 🎉:

Screenshot 2021-06-10 at 15 43 02

Screenshot 2021-06-10 at 15 42 32

### CODE REVIEW

**Comment by vickis** [comment]
super! :D

**Comment by helenvarley** [comment]
great - how can we test it? i just looked for it on dev-app but i guess it's not there yet ... ? anyway this will be great! :sunglasses:

**Review by paul-rohrlach — APPROVED** [review]

**Comment by nguyenhongphat0** [comment]
It's now on devapp: https://dev-app1.upstage.org.nz/V4.0/ui/ 🎉

**Comment by helenvarley** [comment]
great! i uploaded a new image to use as cover, and by default it saved it as an avatar. i didn't notice until i had already hit save. this is not so terrible as we can change the media type (which is a very useful feature, previously we could not do this & sometimes that was annoying), but maybe the default media type when you upload a cover image should be backdrop?

and, in the media list, i see the image that i uploaded as a cover image for my stage, but it does not show as being assigned to any stage. when i go into the edit interface for the media item and look at the stages tab, it also does not show that this is set as the cover image for my stage. this could be confusing because sometimes we use that information to decide what media to delete - if it is showing as not assigned to a stage.

if the cover image shows as being assigned to the stage, but is not actually an available media item on that stage (unless you specifically assign it to that stage - & how do you do this if it is already showing as being assigned ... ) - should assigning a cover image automatically also assign it as a backdrop on that stage? @vickis - thoughts?

**Comment by nguyenhongphat0** [comment]
Well I made cover image as an attribute of the stage (like name and description) rather than an media of the stage 😅 And you can choose any existing image to be the cover image, regardless of type. Should I create another media type, and call it "cover" 🤔

**Comment by vickis** [comment]
Yes i think it could e assigned as backdrop and then available as cover
image

you would likely use it in the show ... although as cover image it might
preview a scene so also have a couple of avatars standing around etc

It the best immediate solution   would be default to backdrop :)

**Pull request merged**
