### PR TITLE
Visual Identity

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
- New toolbox proposed by Elisa
- Fill svg icon color based on Riad design

### CODE REVIEW

**Comment by paul-rohrlach** [comment]
@nguyenhongphat0 this is a change, right?  Not a bug fix?

**Comment by nguyenhongphat0** [comment]
It's hard to tell 🤔 Elisa proposed this a long time ago, and the current icon on the stage look weird without these changes. I think include on R1-2021 release is okay. What do you think Paul?

**Comment by paul-rohrlach** [comment]
What's your goal here?  This does more than just change the icons

**Comment by nguyenhongphat0** [comment]
It change the toolbox also:
Screenshot 2021-03-20 at 22 57 20

**Comment by paul-rohrlach** [comment]
So it's a purely visual change?

**Review by paul-rohrlach — APPROVED** [review]
@gloriajw We'll let this go through - Doesn't look like it impacts functionality in particular

**Comment by nguyenhongphat0** [comment]
Thank you @paul-rohrlach 🥇

**Pull request merged**
