### PR TITLE
Issue 218 Upload Limit

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
- Prevent upload file lagger than 1Mb
- New Admin section: Upload Limit, admin can override user's upload limit up to 100Mb
- Add column `upload_limit` to `upstage_user` table and drop `phone`, `ok_to_sms column` from `upstage_user`

### CODE REVIEW

**Review by gloriajw — APPROVED** [review]

**Comment by gloriajw** [comment]
@nguyenhongphat0 one thing: make sure the nginx limit is >= whatever max value you are allowing systemwide.

**Comment by nguyenhongphat0** [comment]
Thank you Gloria, I'll check this 👌

**Comment by nguyenhongphat0** [comment]
The nginx limit is 300M, Gloria. It's okay since the max value allowed to override is 100M

**Comment by helenvarley** [comment]
can we have a tip added beside the "choose a file" button in the media upload interface, that says "Maximum file size: 1MB"
(it would also be good to say "Supported file formats: .jpg, .png, .gif, .mp3, etc ... i don't know all the file formats - i guess we can add this later? or we know already what is supported?)

**Pull request merged**
