### PR TITLE
Issue 35 Assign stages to media

### PR DESCRIPTION
**Pull request by nguyenhongphat0**
Screenshot 2021-05-18 at 15 46 42

### CODE REVIEW

**Comment by elisadcg** [comment]
i think it's better to only be able to assign media to a Stage in wich we are player with edit access.

**Comment by vickis** [comment]
yes totally agree :)

**Comment by helenvarley** [comment]
this looks great, @nguyenhongphat0 - but i'm a bit concerned about the amount of space; do the buttons for each stage need to be so big? (height)  - there are already a lot of stages so it means a lot of scrolling. can the list be alphabeticised?
& are you making the media type into a dropdown menu? this could go on the same line as the media name - that input field doesn't need to be so long.

**Comment by helenvarley** [comment]
> i think it's better to only be able to assign media to a Stage in wich we are player with edit access.

yes absolutely - is it possible to have only those stages that you have edit access to displaying here? that would help with my concern (above) about having a great long list to scroll through ...

**Review by gloriajw — APPROVED** [review]

**Comment by nguyenhongphat0** [comment]
Sorry, I totally forgot about player access stuff 🤣 And yes, I will make the list more compact. Are there anything else did I missed 😅

**Comment by vickis** [comment]
Great work Phat!

**Pull request merged**
